### ISSUE TITLE
Scenarios expressief documenteren

### ISSUE THREAD

**Issue by MelvLee** [BRP-API/brp-shared#10]
Als stakeholder van de BRP API
Wil ik dat de scenarios/voorbeelden meer begrijpbaar worden gedocumenteerd
Zodat ook afnemers van de BRP API de scenarios/voorbeelden kunnen begrijpen

Voorbeeld:

```
    Gegeven de persoon met burgerservicenummer '000000012'
    * is minderjarig
    * heeft geslacht man
    * is geboren in het buitenland
    * staat geregistreerd in het RNI
    En de persoon heeft een ouder '1' met burgerservicenummer '000000013' met kenmerken
    * is meerderjarig
    * geslachtsnaam onbekend
    En de persoon heeft een ouder '2' met burgerservicenummer '000000014'
    * heeft een document met de volgende gegevens
    | beschrijving document (82.30) | ingangsdatum geldigheid (85.10) |
    | PKA                           | 0                               |
    En de persoon heeft een kind met burgerservicenummer '000000015'
    * heeft een document met de volgende gegevens
    | aktenummer (81.20) | ingangsdatum geldigheid(85.10) |
    | 1AA0002            | 20151201                       |
    * heeft de volgende naam gegevens
    | geslachtsnaam (02.40) | voornamen (02.10) |
    | Arendsen              | Alexa             |
```

Voorbeelden uit [brp-api-gezag#59](https://github.com/BRP-API/brp-api-gezag/issues/59) herschreven:

```
  Scenario: minderjarige
    Gegeven de persoon 'P1' met burgerservicenummer '000000012'
    * staat ingeschreven in Nederland
    * heeft de volgende geboorte gegevens
    | geboortedatum (03.10) | geboorteland (03.30) |
    | minderjarig           | 6030                 |
    # of
    * is geboren in Nederland
    * is minderjarig

  Scenario: minderjarige met 2 ouders (niet gehuwd)
    Gegeven de persoon 'P1' met burgerservicenummer '000000012'
    En de persoon 'P2' met burgerservicenummer '000000013'
    En de persoon 'P3' met burgerservicenummer '000000014'
    * is minderjarig
    * is geboren in Nederland
    * heeft persoon 'P1' als ouder1
    | aktenummer (81.20) |
    | 3AA0001            |
    * heeft persoon 'P2' als ouder2 met de volgende gegevens
    | aktenummer (81.20) |
    | 3AA0001            |

  Scenario: minderjarige met 2 ouders (gehuwd/geregistreerd partnerschap)
    Gegeven de persoon 'P1' met burgerservicenummer '000000012'
    En de persoon 'P2' met burgerservicenummer '000000013'
    En persoon 'P1' is gehuwd met persoon 'P2'
    | datum huwelijkssluiting/aangaan geregistreerd partnerschap (06.10) |
    | gisteren - 20 jaar                                                 |
    En de persoon 'P3' met burgerservicenummer '000000014'
    * heeft de volgende geboorte gegevens
    | geboortedatum (03.10) | geboorteland (03.30) |
    | morgen - 18 jaar      | 6030                 |
    * heeft persoon 'P1' als ouder1
    | aktenummer (81.20) |
    | 3AA0001            |
    * heeft persoon 'P2' als ouder2
    | aktenummer (81.20) |
    | 3AA0001            |

  Scenario: minderjarige staat ingeschreven in RNI (vraag 1.1 - nee)
    Gegeven de persoon 'P1' met burgerservicenummer '000000012'
    En de persoon 'P2' met burgerservicenummer '000000013'
    En persoon 'P1' heeft geregistreerd partnerschap met persoon 'P2'
    | datum huwelijkssluiting/aangaan geregistreerd partnerschap (06.10) |
    | gisteren - 20 jaar                                                 |
    En de persoon 'P3' met burgerservicenummer '000000014'
    * heeft de volgende geboorte gegevens
    | geboortedatum (03.10) | geboorteland (03.30) |
    | morgen - 18 jaar      | 6030                 |
    * heeft persoon 'P1' als ouder1
    | aktenummer (81.20) |
    | 3AA0001            |
    * heeft persoon 'P2' als ouder2
    | aktenummer (81.20) |
    | 3AA0001            |
    * was ingeschreven in Nederland
    * staat vervolgens geregistreerd in het RNI

  Scenario: Ouders zijn nooit met elkaar getrouwd of partners geweest en minderjarige is geadopteerd door beide ouders (vraag 2a.2 - ja)
    Gegeven de persoon 'P1' met burgerservicenummer '000000012'
    En de persoon 'P2' met burgerservicenummer '000000013'
    En de persoon 'P3' met burgerservicenummer '000000014'
    * is geadopteerd volgens de volgende akte
    | aktenummer (81.20) | ingangsdatum geldigheid(85.10) |
    | 1VQ0700            | 20240703                       |
    * heeft persoon 'P1' als ouder1
    | aktenummer (81.20) |
    | 3AA0001            |
    * heeft persoon 'P2' als ouder2
    | aktenummer (81.20) |
    | 3AA0001            |

```

Benodigde aanpassingen/uitbreidingen

- [ ] `features/step_definitions/gezag.js` aanmaken voor uit te voeren acties met betrekking tot gezagsrelaties

`features/step_definitions/gegeven-stepdefs-persoon.js` uitbreiden met
- [x] is minderjarig
- [ ] heeft geslacht [geslachtsaanduiding]
- [x] is in het buitenland geboren
- [x] is in Nederland geboren
- [x] heeft persoon [aanduiding] als ouder1 vanaf de geboorteaangifte
- [x] is ingeschreven in de de BRP (met ondersteuning voor waardetabel)
- [x] is ingeschreven in de de BRP heeft de impliciete eigenschap dat gemeente_code **niet gelijk is aan** 1999 (wat moet het dan wel zijn?)
- [x] staat geregistreerd in het RNI (welke inserts zijn hiervoor vereist?)

Voorstel is de volgende stappen te gebruiken, die de vragen uit het stroomschema volgen:
| implemented | stap | data gevolgen| dataTable |
|--- |--- |--- |--- |
| X | de persoon '(\*)' met burgerservicenummer '(\d*)' | zelfde als "de persoon met burgerservicenummer '(\d*)"| optioneel >> persoon[P] |
| X | is ingeschreven in de BRP | verblijfplaats: gemeente van inschrijving (09.10) = 518 | optioneel, >> verblijfplaats |
| X | is ingeschreven in de RNI | verblijfplaats: gemeente van inschrijving (09.10) = 1999 | optioneell, >> verblijfplaats |
| X | is minderjarig | persoon[P]: geboortedatum (03.10) = morgen - 17 jaar | optioneel >> persoon[P] |
| X | is meerderjarig | persoon[P]: geboortedatum (03.10) = gisteren - 35 jaar | optioneel >> persoon[P] |
| X | is niet geëmigreerd geweest | geen | niet|
| X | is in Nederland geboren| persoon[P]: geboorteland (03.30) = 6030, aktenummer (81.20) = 1AA0100 | niet |
| X | heeft geen uitspraak gezag | geen |niet|
| X | heeft gezag uitspraak | uit dataTable | >> gezagsverhouding |
| X | heeft een ouder '(.*)' met burgerservicenummer '(.*)' | persoon[1/2] met gegevens van de ouder, persoon[K] met gegevens van het kind | niet|
| | heeft een juridische ouder '(\.*)' met burgerservicenummer '(\d*)' | nieuwe PL voor de ouder met burgerservicenummer (01.20), geboortedatum (03.10) = gisteren - 30 jaar, geslachtsnaam (02.40) = "Voorbeeld", persoon[K] van de ouder met burgerservicenummer en geboortedatum van persoon, persoon[1/2] van de persoon met burgerservicenummer en geslachtsnaam van ouders en aktenummer (81.20) = 1AA0100 | optioneel, >> persoon[1/2]|
|X | '(.*)' en '(.*)' zijn met elkaar gehuwd | persoon[R] voor elk van ouders (vorige stap) met naam en burgerservicenummer van andere ouder en datum huwelijkssluiting/aangaan geregistreerd partnerschap (06.10) = gisteren - 2 jaar | niet |
|X | beide ouders zijn nooit met elkaar getrouwd geweest en hebben nooit een geregistreerd partnerschap gehad | geen | niet |
| X| beide ouders zijn meerderjarig, niet overleden en staan niet onder curatele | geen | niet |
| | heeft de volgende gegevens | dataTable | persoon[P]  |
| | zijn de volgende gegevens gewijzigd |  *nieuw voorkomen* persoon[P] is kopie van bestaande | >> persoon[P] |
| X | is geëmigreerd geweest | datum vestiging in Nederland (14.20) =  gisteren - 1 jaar | optioneel, >> verblijfplaats|
| | is geadopteerd door beide ouders | *nieuw voorkomen* persoon[1+2]: aktenummer (81.20) = 1AQ0100, datum ingang familierechtelijke betrekking (62.10) = gisteren - 1 jaar | optioneel, >> persoon[1+2] |
| | is geadopteerd door ouder '(.*)' | *nieuw voorkomen* persoon[1/2]: aktenummer (81.20) = 1AQ0100, datum ingang familierechtelijke betrekking (62.10) = gisteren - 1 jaar | optioneel, >> persoon[1/2] |
| | heeft de volgende gegevens voor ouder '(.*)' |  | >> persoon[1/2] |
| | de volgende gegevens voor ouder '(.*)' zijn gecorrigeerd | *nieuw voorkomen* persoon[1/2] is kopie van bestaande, bestaande wordt historisch en krijgt indicatie onjuist (84.10) = "O" | >> persoon[1/2] |

- op een aantal plekken is een data tabel optioneel. (is dan ook aangegeven)
- wanneer de data tabel aanwezig is, vult dit gegevens van die categorie aan of overschrijft die wanneer die in een eerdere stap of de default data gevolgen van deze stap al zijn aangemaakt.
- wanneer in de data tabel de waarde leeg is (alleen spaties in de feature stap), wordt dit als null in de database gezet.
- waar staat "nieuw voorkomen" wordt de daarvoor beschreven categorie historisch (volgnummer + 1) en wordt een nieuwe actuele gemaakt (volg_nr=0), zoals gebeurt in teststap "de persoon is gewijzigd naar de volgende gegevens". Alleen worden gegevens van gekopieerd en alleen gegevens die in de dataTable voorkomen overschreven.

**Comment by fsamwel** [comment]
@MelvLee ik vind de gegevenstappen op deze manier duidelijk. personen aanduiden met een P-nummer maakt dit denk ik duidelijker. Ik ga https://github.com/BRP-API/brp-api-gezag/pull/4 en https://github.com/BRP-API/brp-api-gezag/pull/65 herschrijven gebaseerd op deze voorbeelden.

**Comment by fsamwel** [comment]
@MelvLee hoeveel mag ik hierbij aannemen als impliciet ingevuld bij de stap "Gegeven de persoon 'P1' met burgerservicenummer '000000012'"?
- heeft geslachtsnaam ingevuld?
- is meerderjarig?

Of vult deze stap helemaal niks van de persoon, behalve indicatie geheim 0 en het burgerservicenummer, zoals we bij eerdere stappen gedaan hebben?

**Comment by fsamwel** [comment]
@CathyDingemanse @MelvLee ik heb de Gegeven stappen aangepast in https://github.com/BRP-API/brp-api-gezag/blob/1db80ac5e64d366938348aa3e530a31098668203/features/gezag-minderjarige/1.1-ingezetene-BRP.feature zoals hier voorgesteld. Is dit hoe jullie het bedoelen/willen?

Een paar opmerkingen:
- ik heb de stap `is geregistreerd met de geboorteakte` verzonnen, om duidelijk te maken dat het aktenummer dat eronder staat een geboorteakte is (dus geen adoptie)
- ik heb de stap voor toevoegen van een ouder aangevuld naar `heeft persoon 'P1' als ouder1 vanaf de geboorteaangifte`. Door deze aanvulling moet ook datum ingang familierechtelijke betrekking (62.10) gevuld worden met de geboortedatum.
- ik heb de stappen `is ingeschreven in de de RNI` of `is ingeschreven in de de BRP` hier aangevuld met een waardetabel met gemeente van inschrijving (09.10) om specifiek voor deze feature te tonen dat we kijken naar alleen dat veld om te bepalen of de persoon in RNI dan wel BRP staat ingeschreven. 
- ook voeg ik in een van de scenario's aanduiding in onderzoek (83.10) toe aan diezelfde waardetabel, om de situatie te tonen dat gemeente van inschrijving in onderzoek staat.
- In volgende features kan de stap `is ingeschreven in de de BRP` impliciet een gemeente van inschrijving ongelijk aan 1999 toevoegen zonder deze waardetabel.

**Comment by fsamwel** [comment]
@MelvLee hoe moeten de gegeven stappen worden opgenomen wanneer we vragen van gezag van een meerderjarige willen tonen?
Hierboven staat als stap `En de persoon heeft een kind met burgerservicenummer '000000015'`
Liever zou ik dat ook als referentie van P-nummer doen: `En persoon 'P1' heeft een kind 'P2'`

**Comment by MelvLee** [comment]
> @MelvLee hoe moeten de gegeven stappen worden opgenomen wanneer we vragen van gezag van een meerderjarige willen tonen? Hierboven staat als stap `En de persoon heeft een kind met burgerservicenummer '000000015'` Liever zou ik dat ook als referentie van P-nummer doen: `En persoon 'P1' heeft een kind 'P2'

Dit kan als stap worden toegevoegd

**Comment by nielskorporaal** [comment]
Mogelijke **nieuwe** vormen van notatie


### Persoon met burgerservicenummer

Notatie zonder aanduiding
- `Gegeven de persoon met burgerservicenummer '000000012'`

Met aanduiding
- `Gegeven de persoon 'P1' met burgerservicenummer '000000012'`

Aanduiding kan bestaan uit meerdere woorden
- `Gegeven de persoon 'Alex Adema' met burgerservicenummer '000000012'`

Notatie met 'En'
- `En de persoon met burgerservicenummer '000000012`

'En' kan vervangen worden met '*' ten behoeve van de leesbaarheid
- `* de persoon met burgerservicenummer '000000012'`

### Aanvullende persoonlijke informatie

Persoon is minderjarig / meerderjarig

- `* de persoon 'P1' is minderjarig`
- `* de persoon is minderjarig`
- `* is minderjarig`

Persoon is in Nederland geboren

- `* de persoon 'P1' is in Nederland geboren`
- `* de persoon is in Nederland geboren`
- `* is in Nederland geboren`

Persoon heeft geen uitspraak gezag

- `* de persoon 'P1' heeft geen uitspraak gezag`
- `* de persoon heeft geen uitspraak gezag`
- `* heeft geen uitspraak gezag`

Persoon heeft gezag

- `* de persoon 'P1' heeft uitspraak gezag met de volgende gegevens` gevolgd door een dataTable
- `* de persoon heeft uitspraak gezag met de volgende gegevens` gevolgd door een dataTable
- `* heeft uitspraak gezag met de volgende gegevens` gevolgd door een dataTable

Persoon is niet geëmigreerd geweest

- `* de persoon 'P1' is niet geëmigreerd geweest`
- `* de persoon is niet geëmigreerd geweest`
- `* is niet geëmigreerd geweest`

Persoon is geëmigreerd geweest

- `* de persoon 'P1' is geëmigreerd geweest`
- `* de persoon is geëmigreerd geweest`
- `* is geëmigreerd geweest`
- `* is geëmigreerd geweest met de volgende gegevens` gevolgd door een dataTable

Persoon is ingeschreven in de BRP / RNI

- `* de persoon 'P1' is ingeschreven in de BRP`
- `* de persoon is ingeschreven in de BRP`
- `* is ingeschreven in de BRP`
- `* is ingeschreven in de BRP met de volgende gegevens` gevolgd door een dataTable

**Comment by fsamwel** [comment]
Voor [vraag 3.1](https://github.com/BRP-API/brp-api-gezag/pull/81) gebruik ik de volgende stappen:

1. de persoon '(.*)' met burgerservicenummer '(\d*)'
2. is ingeschreven in de BRP
3. is minderjarig
4. is niet geëmigreerd geweest
5. is in Nederland geboren
6. heeft een ouder '(.*)' met met burgerservicenummer '(\d*)'
7. (.*)' en '(.*)' zijn met elkaar gehuwd
8. beide ouders zijn meerderjarig, niet overleden en staan niet onder curatele
9. heeft gezag uitspraak
10. is geadopteerd
11. zijn de volgende gegevens van ouder '(.*)' gewijzigd
12. zijn de volgende gegevens gewijzigd
13. zijn de volgende gegevens gecorrigeerd
14. (.*)' en '(.*)' zijn gescheiden
15. is het huwelijk van '(.*)' en '(.*)' gecorrigeerd

**Comment by nielskorporaal** [comment]
- [x] 1. de persoon '(.*)' met burgerservicenummer '(\d*)'
- [x] 2. is ingeschreven in de BRP
- [x] 3. is minderjarig
- [x] 4. is niet geëmigreerd geweest
- [x] 5. is in Nederland geboren
- [x] 6. heeft een ouder '(.*)' met burgerservicenummer '(\d*)'
- [x] 7. (.*)' en '(.*)' zijn met elkaar gehuwd
- [x] 8. beide ouders zijn meerderjarig, niet overleden en staan niet onder curatele
- [x] 9. heeft gezag uitspraak
- [x] 10. is geadopteerd
- [x] 11. zijn de volgende gegevens van ouder '(.*)' gewijzigd
- [x] 12. zijn de volgende gegevens gewijzigd
- [x] 13. zijn de volgende gegevens gecorrigeerd
- [x] 14. (.*)' en '(.*)' zijn gescheiden
- [ ] 15. is het huwelijk van '(.*)' en '(.*)' gecorrigeerd (pending)
